export const Constant = {
    department: [
        { color: "#dc9593", icon: "medkit-outline", title: "General Medicine" },
        { color: "#93c09f", icon: "bandage-outline", title: "General Surgery" },
        { color: "#f1ae7f", icon: "happy-outline", title: "Pediatrics" },
        { color: "#aba1cc", icon: "female-outline", title: "Obstetrics and Gynecology" },
        { color: "#4c9c92", icon: "walk-outline", title: "Orthopedics" },
        { color: "#332360", icon: "eye-outline", title: "Ophthalmology" },
        { color: "#dfb6b4", icon: "mic-outline", title: "Otolaryngology" },
        { color: "#86ceda", icon: "color-palette-outline", title: "Dermatology" },
        { color: "#f78ca2", icon: "chatbubbles-outline", title: "Psychiatry" },
        { color: "#ffd56b", icon: "radio-outline", title: "Radiology" },
        { color: "#98ddca", icon: "flame-outline", title: "Anesthesiology" },
        { color: "#c3bef0", icon: "cloud-outline", title: "Pulmonology" },
        { color: "#ffa69e", icon: "heart-outline", title: "Cardiology" },
        { color: "#a0ced9", icon: "pulse-outline", title: "Neurology" },
        { color: "#b8bedd", icon: "water-outline", title: "Nephrology" },
        { color: "#f7c59f", icon: "restaurant-outline", title: "Gastroenterology" },
        { color: "#e0bbe4", icon: "male-female-outline", title: "Urology" },
        { color: "#c6d8d3", icon: "thermometer-outline", title: "Endocrinology" },
        { color: "#eac4d5", icon: "fitness-outline", title: "Rheumatology" }
    ],
    odisha_districts: [
        "Angul",
        "Balangir",
        "Balasore",
        "Bargarh",
        "Bhadrak",
        "Boudh",
        "Cuttack",
        "Deogarh",
        "Dhenkanal",
        "Gajapati",
        "Ganjam",
        "Jagatsinghpur",
        "Jajpur",
        "Jharsuguda",
        "Kalahandi",
        "Kandhamal",
        "Kendrapara",
        "Kendujhar",
        "Khordha",
        "Koraput",
        "Malkangiri",
        "Mayurbhanj",
        "Nabarangpur",
        "Nayagarh",
        "Nuapada",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Sonepur",
        "Sundargarh"
    ]
}